// 2025 Water-logging/Weather data for Telangana districts
export interface AreaData {
  area: string
  areaHi: string
  months: {
    month: string
    rainfall: number
    verdict: "high" | "mid" | "low"
  }[]
}

export const areas = [
  "Hyderabad",
  "Rangareddy",
  "Medchal-Malkajgiri",
  "Sangareddy",
  "Nizamabad",
  "Karimnagar",
  "Warangal",
  "Khammam",
  "Nalgonda",
  "Mahbubnagar",
  "Adilabad",
  "Nirmal",
] as const

export const areasTelugu = [
  "హైదరాబాద్",
  "రంగారెడ్డి",
  "మేడ్చల్-మల్కాజ్‌గిరి",
  "సంగారెడ్డి",
  "నిజామాబాద్",
  "కరీంనగర్",
  "వరంగల్",
  "ఖమ్మం",
  "నల్గొండ",
  "మహబూబ్‌నగర్",
  "ఆదిలాబాద్",
  "నిర్మల్",
]

export const monthNames = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

export const waterLoggingData2025: AreaData[] = [
  {
    area: "Hyderabad",
    areaHi: "హైదరాబాద్",
    months: [
      { month: "Jan", rainfall: 12, verdict: "low" },
      { month: "Feb", rainfall: 10, verdict: "low" },
      { month: "Mar", rainfall: 15, verdict: "low" },
      { month: "Apr", rainfall: 20, verdict: "low" },
      { month: "May", rainfall: 35, verdict: "low" },
      { month: "Jun", rainfall: 95, verdict: "mid" },
      { month: "Jul", rainfall: 190, verdict: "high" },
      { month: "Aug", rainfall: 210, verdict: "high" },
      { month: "Sep", rainfall: 175, verdict: "high" },
      { month: "Oct", rainfall: 85, verdict: "mid" },
      { month: "Nov", rainfall: 22, verdict: "low" },
      { month: "Dec", rainfall: 8, verdict: "low" },
    ],
  },
  {
    area: "Rangareddy",
    areaHi: "రంగారెడ్డి",
    months: [
      { month: "Jan", rainfall: 10, verdict: "low" },
      { month: "Feb", rainfall: 9, verdict: "low" },
      { month: "Mar", rainfall: 12, verdict: "low" },
      { month: "Apr", rainfall: 18, verdict: "low" },
      { month: "May", rainfall: 30, verdict: "low" },
      { month: "Jun", rainfall: 88, verdict: "mid" },
      { month: "Jul", rainfall: 185, verdict: "high" },
      { month: "Aug", rainfall: 200, verdict: "high" },
      { month: "Sep", rainfall: 165, verdict: "high" },
      { month: "Oct", rainfall: 80, verdict: "mid" },
      { month: "Nov", rainfall: 18, verdict: "low" },
      { month: "Dec", rainfall: 6, verdict: "low" },
    ],
  },
  {
    area: "Medchal-Malkajgiri",
    areaHi: "మేడ్చల్-మల్కాజ్‌గిరి",
    months: [
      { month: "Jan", rainfall: 11, verdict: "low" },
      { month: "Feb", rainfall: 9, verdict: "low" },
      { month: "Mar", rainfall: 13, verdict: "low" },
      { month: "Apr", rainfall: 19, verdict: "low" },
      { month: "May", rainfall: 32, verdict: "low" },
      { month: "Jun", rainfall: 90, verdict: "mid" },
      { month: "Jul", rainfall: 188, verdict: "high" },
      { month: "Aug", rainfall: 205, verdict: "high" },
      { month: "Sep", rainfall: 170, verdict: "high" },
      { month: "Oct", rainfall: 82, verdict: "mid" },
      { month: "Nov", rainfall: 20, verdict: "low" },
      { month: "Dec", rainfall: 7, verdict: "low" },
    ],
  },
  {
    area: "Sangareddy",
    areaHi: "సంగారెడ్డి",
    months: [
      { month: "Jan", rainfall: 9, verdict: "low" },
      { month: "Feb", rainfall: 8, verdict: "low" },
      { month: "Mar", rainfall: 11, verdict: "low" },
      { month: "Apr", rainfall: 16, verdict: "low" },
      { month: "May", rainfall: 28, verdict: "low" },
      { month: "Jun", rainfall: 82, verdict: "mid" },
      { month: "Jul", rainfall: 170, verdict: "high" },
      { month: "Aug", rainfall: 190, verdict: "high" },
      { month: "Sep", rainfall: 155, verdict: "high" },
      { month: "Oct", rainfall: 72, verdict: "mid" },
      { month: "Nov", rainfall: 16, verdict: "low" },
      { month: "Dec", rainfall: 5, verdict: "low" },
    ],
  },
  {
    area: "Nizamabad",
    areaHi: "నిజామాబాద్",
    months: [
      { month: "Jan", rainfall: 8, verdict: "low" },
      { month: "Feb", rainfall: 7, verdict: "low" },
      { month: "Mar", rainfall: 10, verdict: "low" },
      { month: "Apr", rainfall: 15, verdict: "low" },
      { month: "May", rainfall: 30, verdict: "low" },
      { month: "Jun", rainfall: 100, verdict: "mid" },
      { month: "Jul", rainfall: 210, verdict: "high" },
      { month: "Aug", rainfall: 230, verdict: "high" },
      { month: "Sep", rainfall: 180, verdict: "high" },
      { month: "Oct", rainfall: 78, verdict: "mid" },
      { month: "Nov", rainfall: 18, verdict: "low" },
      { month: "Dec", rainfall: 6, verdict: "low" },
    ],
  },
  {
    area: "Karimnagar",
    areaHi: "కరీంనగర్",
    months: [
      { month: "Jan", rainfall: 10, verdict: "low" },
      { month: "Feb", rainfall: 8, verdict: "low" },
      { month: "Mar", rainfall: 12, verdict: "low" },
      { month: "Apr", rainfall: 18, verdict: "low" },
      { month: "May", rainfall: 32, verdict: "low" },
      { month: "Jun", rainfall: 98, verdict: "mid" },
      { month: "Jul", rainfall: 200, verdict: "high" },
      { month: "Aug", rainfall: 220, verdict: "high" },
      { month: "Sep", rainfall: 195, verdict: "high" },
      { month: "Oct", rainfall: 88, verdict: "mid" },
      { month: "Nov", rainfall: 20, verdict: "low" },
      { month: "Dec", rainfall: 7, verdict: "low" },
    ],
  },
  {
    area: "Warangal",
    areaHi: "వరంగల్",
    months: [
      { month: "Jan", rainfall: 12, verdict: "low" },
      { month: "Feb", rainfall: 10, verdict: "low" },
      { month: "Mar", rainfall: 14, verdict: "low" },
      { month: "Apr", rainfall: 20, verdict: "low" },
      { month: "May", rainfall: 35, verdict: "low" },
      { month: "Jun", rainfall: 105, verdict: "mid" },
      { month: "Jul", rainfall: 220, verdict: "high" },
      { month: "Aug", rainfall: 240, verdict: "high" },
      { month: "Sep", rainfall: 200, verdict: "high" },
      { month: "Oct", rainfall: 92, verdict: "mid" },
      { month: "Nov", rainfall: 22, verdict: "low" },
      { month: "Dec", rainfall: 8, verdict: "low" },
    ],
  },
  {
    area: "Khammam",
    areaHi: "ఖమ్మం",
    months: [
      { month: "Jan", rainfall: 14, verdict: "low" },
      { month: "Feb", rainfall: 12, verdict: "low" },
      { month: "Mar", rainfall: 16, verdict: "low" },
      { month: "Apr", rainfall: 22, verdict: "low" },
      { month: "May", rainfall: 40, verdict: "mid" },
      { month: "Jun", rainfall: 115, verdict: "high" },
      { month: "Jul", rainfall: 250, verdict: "high" },
      { month: "Aug", rainfall: 270, verdict: "high" },
      { month: "Sep", rainfall: 220, verdict: "high" },
      { month: "Oct", rainfall: 100, verdict: "mid" },
      { month: "Nov", rainfall: 28, verdict: "low" },
      { month: "Dec", rainfall: 10, verdict: "low" },
    ],
  },
  {
    area: "Nalgonda",
    areaHi: "నల్గొండ",
    months: [
      { month: "Jan", rainfall: 9, verdict: "low" },
      { month: "Feb", rainfall: 8, verdict: "low" },
      { month: "Mar", rainfall: 11, verdict: "low" },
      { month: "Apr", rainfall: 16, verdict: "low" },
      { month: "May", rainfall: 28, verdict: "low" },
      { month: "Jun", rainfall: 80, verdict: "mid" },
      { month: "Jul", rainfall: 165, verdict: "high" },
      { month: "Aug", rainfall: 185, verdict: "high" },
      { month: "Sep", rainfall: 155, verdict: "high" },
      { month: "Oct", rainfall: 75, verdict: "mid" },
      { month: "Nov", rainfall: 16, verdict: "low" },
      { month: "Dec", rainfall: 5, verdict: "low" },
    ],
  },
  {
    area: "Mahbubnagar",
    areaHi: "మహబూబ్‌నగర్",
    months: [
      { month: "Jan", rainfall: 8, verdict: "low" },
      { month: "Feb", rainfall: 7, verdict: "low" },
      { month: "Mar", rainfall: 9, verdict: "low" },
      { month: "Apr", rainfall: 14, verdict: "low" },
      { month: "May", rainfall: 25, verdict: "low" },
      { month: "Jun", rainfall: 75, verdict: "mid" },
      { month: "Jul", rainfall: 155, verdict: "high" },
      { month: "Aug", rainfall: 175, verdict: "high" },
      { month: "Sep", rainfall: 145, verdict: "high" },
      { month: "Oct", rainfall: 68, verdict: "mid" },
      { month: "Nov", rainfall: 14, verdict: "low" },
      { month: "Dec", rainfall: 4, verdict: "low" },
    ],
  },
  {
    area: "Adilabad",
    areaHi: "ఆదిలాబాద్",
    months: [
      { month: "Jan", rainfall: 10, verdict: "low" },
      { month: "Feb", rainfall: 9, verdict: "low" },
      { month: "Mar", rainfall: 12, verdict: "low" },
      { month: "Apr", rainfall: 17, verdict: "low" },
      { month: "May", rainfall: 35, verdict: "low" },
      { month: "Jun", rainfall: 120, verdict: "high" },
      { month: "Jul", rainfall: 260, verdict: "high" },
      { month: "Aug", rainfall: 285, verdict: "high" },
      { month: "Sep", rainfall: 215, verdict: "high" },
      { month: "Oct", rainfall: 88, verdict: "mid" },
      { month: "Nov", rainfall: 22, verdict: "low" },
      { month: "Dec", rainfall: 7, verdict: "low" },
    ],
  },
  {
    area: "Nirmal",
    areaHi: "నిర్మల్",
    months: [
      { month: "Jan", rainfall: 9, verdict: "low" },
      { month: "Feb", rainfall: 8, verdict: "low" },
      { month: "Mar", rainfall: 11, verdict: "low" },
      { month: "Apr", rainfall: 16, verdict: "low" },
      { month: "May", rainfall: 32, verdict: "low" },
      { month: "Jun", rainfall: 110, verdict: "high" },
      { month: "Jul", rainfall: 240, verdict: "high" },
      { month: "Aug", rainfall: 260, verdict: "high" },
      { month: "Sep", rainfall: 200, verdict: "high" },
      { month: "Oct", rainfall: 80, verdict: "mid" },
      { month: "Nov", rainfall: 19, verdict: "low" },
      { month: "Dec", rainfall: 6, verdict: "low" },
    ],
  },
]

// Calculate average rainfall per month across all areas
export function getAverageRainfallData() {
  const avgData = monthNames.map((month, idx) => {
    const total = waterLoggingData2025.reduce((sum, area) => sum + area.months[idx].rainfall, 0)
    return {
      month,
      rainfall: Math.round(total / waterLoggingData2025.length),
    }
  })
  return avgData
}

export const newsWithImages = [
  {
    id: 1,
    title: "IMD Issues Red Alert for Hyderabad and Rangareddy; Heavy Rainfall Predicted",
    titleHi: "IMD హైదరాబాద్ మరియు రంగారెడ్డికి రెడ్ అలర్ట్ జారీ చేసింది; భారీ వర్షాలు అంచనా",
    date: "Jan 15, 2025",
    excerpt: "The Meteorological Department has warned of extremely heavy rainfall in various parts of Telangana.",
    image: "/images/hp-rains-alert.png",
  },
  {
    id: 2,
    title: "Musi River Overflows; Low-Lying Areas in Hyderabad Flooded",
    titleHi: "మూసీ నది పొంగిపొర్లింది; హైదరాబాద్‌లో తక్కువ ప్రాంతాలు నీట మునిగాయి",
    date: "Jan 14, 2025",
    excerpt: "Musi River breaches danger level, affecting colonies along the riverbank in Hyderabad.",
    image: "/images/hp-highway-block.png",
  },
  {
    id: 3,
    title: "Godavari River Flows Above Danger Mark; Khammam Districts on Alert",
    titleHi: "గోదావరి నది ప్రమాద స్థాయి మించింది; ఖమ్మం జిల్లాలు అప్రమత్తంగా ఉన్నాయి",
    date: "Jan 13, 2025",
    excerpt: "Rising water levels in Godavari and Krishna rivers pose threat to low-lying villages in Khammam.",
    image: "/images/beas-river-flood.png",
  },
  {
    id: 4,
    title: "Cloudburst Reported in Adilabad; Rescue Operations Underway",
    titleHi: "ఆదిలాబాద్‌లో మేఘం పగిలింది; సహాయ చర్యలు జరుగుతున్నాయి",
    date: "Jan 12, 2025",
    excerpt: "Flash floods triggered by cloudburst cause damage to property in Adilabad district.",
    image: "/images/hp-cloudburst.png",
  },
  {
    id: 5,
    title: "Telangana Records 60% Excess Rainfall This Week",
    titleHi: "తెలంగాణలో ఈ వారం 60% అదనపు వర్షపాతం నమోదైంది",
    date: "Jan 11, 2025",
    excerpt: "Monsoon activity intensifies across the state, breaking previous records in Warangal and Karimnagar.",
    image: "/images/hp-rainfall-record.png",
  },
  {
    id: 6,
    title: "Telangana State Disaster Management Authority Deploys Teams for Flood Monitoring",
    titleHi: "తెలంగాణ రాష్ట్ర విపత్తు నిర్వహణ సంస్థ వరద పర్యవేక్షణకు బృందాలను నియమించింది",
    date: "Jan 10, 2025",
    excerpt: "TSDMA takes proactive steps to prevent flood losses across Godavari and Krishna basins.",
    image: "/images/hp-glacier.png",
  },
  {
    id: 7,
    title: "Nalgonda Facing Drinking Water Crisis Due to Silt in Reservoirs",
    titleHi: "జలాశయాల్లో పూడిక కారణంగా నల్గొండలో మంచినీటి సంక్షోభం",
    date: "Jan 9, 2025",
    excerpt: "Heavy rains cause high turbidity in water sources, affecting supply in Nalgonda district.",
    image: "/images/hp-rains-alert.png",
  },
  {
    id: 8,
    title: "Government Sets Up 24/7 Emergency Helpline for Flood Victims",
    titleHi: "వరద బాధితులకు ప్రభుత్వం 24/7 అత్యవసర హెల్ప్‌లైన్ ఏర్పాటు చేసింది",
    date: "Jan 8, 2025",
    excerpt: "Special assistance desk for stranded residents in flood-affected areas of Telangana.",
    image: "/images/hp-highway-block.png",
  },
  {
    id: 9,
    title: "Paddy Crops Damaged by Unseasonal Flooding in Nizamabad",
    titleHi: "నిజామాబాద్‌లో అకాల వరదలతో వరి పంటలు దెబ్బతిన్నాయి",
    date: "Jan 7, 2025",
    excerpt: "Farmers in Nizamabad and Sangareddy face losses due to erratic monsoon patterns.",
    image: "/images/hp-cloudburst.png",
  },
  {
    id: 10,
    title: "CM Revanth Reddy Reviews Disaster Preparedness in Hyderabad",
    titleHi: "సీఎం రేవంత్ రెడ్డి హైదరాబాద్‌లో విపత్తు సన్నద్ధతను సమీక్షించారు",
    date: "Jan 5, 2025",
    excerpt: "Chief Minister emphasizes the role of technology in flood and water-logging management.",
    image: "/images/hp-rainfall-record.png",
  },
]
